# Generated by Django 5.2 on 2025-04-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('posto', models.TextField(max_length=100)),
                ('nome', models.TextField(max_length=250)),
                ('funcao', models.TextField(max_length=100)),
                ('senha', models.TextField(max_length=12)),
            ],
        ),
    ]
