# Generated by Django 5.2 on 2025-04-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('posgra', models.TextField(max_length=100)),
                ('nome', models.TextField(max_length=250)),
                ('cnhcat', models.TextField(max_length=10)),
                ('funcao', models.TextField(max_length=100)),
                ('senha', models.TextField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
