# Generated by Django 5.2 on 2025-04-15 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frota', '0005_rename_id_user_veiculo_id_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
