# Generated by Django 5.2 on 2025-04-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frota', '0006_veiculo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
