# Generated by Django 5.2 on 2025-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frota', '0007_alter_usuario_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.TextField(max_length=7),
        ),
    ]
