# Generated by Django 5.2 on 2025-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frota', '0008_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
