# Generated by Django 5.2 on 2025-04-19 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frota', '0009_alter_veiculo_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id_empenho', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('posgra', models.TextField(max_length=100)),
                ('nome', models.TextField(max_length=250)),
                ('placa', models.TextField(max_length=10)),
                ('modelo', models.TextField(max_length=50)),
                ('data_ini', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
