# Generated by Django 5.2 on 2025-05-13 23:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frota', '0010_empenho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('demandante_orgao', models.TextField(max_length=200)),
                ('demandante_pessoa', models.TextField(max_length=250)),
                ('acesso_veiculos', models.BooleanField()),
                ('acesso_pessoas', models.BooleanField()),
                ('acesso_prestadores', models.BooleanField()),
                ('data_agenda', models.DateField(default=datetime.datetime.now)),
                ('obs_agenda', models.TextField(max_length=200)),
                ('confirmada_agenda', models.BooleanField(default=False)),
                ('local_agenda', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'agenda',
                'verbose_name_plural': 'agendas',
                'ordering': ('demandante_orgao',),
            },
        ),
        migrations.CreateModel(
            name='Acesso_Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.TextField(max_length=10)),
                ('marca', models.TextField(max_length=50)),
                ('modelo', models.TextField(max_length=50)),
                ('cor', models.TextField(max_length=10)),
                ('confirmada_veiculo', models.BooleanField(default=False)),
                ('data_acesso', models.DateField(default=datetime.datetime.now)),
                ('id_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frota.agenda', verbose_name='agenda')),
            ],
            options={
                'verbose_name': 'acesso de veiculo',
                'verbose_name_plural': 'acessos de veiculos',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Acesso_Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=250)),
                ('pessoa_ssp', models.TextField(blank=True, max_length=100, null=True)),
                ('pessoa_cpf', models.TextField(blank=True, max_length=10, null=True)),
                ('confirmada_pessoa', models.BooleanField(default=False)),
                ('data_acesso', models.DateField(default=datetime.datetime.now)),
                ('id_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frota.agenda', verbose_name='agenda_')),
            ],
            options={
                'verbose_name': 'acesso de prestador',
                'verbose_name_plural': 'acessos de prestadores',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Acesso_Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=250)),
                ('pessoa_ssp', models.TextField(blank=True, max_length=100, null=True)),
                ('pessoa_cpf', models.TextField(blank=True, max_length=10, null=True)),
                ('confirmada_pessoa', models.BooleanField(default=False)),
                ('data_acesso', models.DateField(default=datetime.datetime.now)),
                ('id_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frota.agenda', verbose_name='agenda')),
            ],
            options={
                'verbose_name': 'acesso de pessoa',
                'verbose_name_plural': 'acessos de pessoas',
                'ordering': ('-pk',),
            },
        ),
    ]
