# Generated by Django 5.2 on 2025-05-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frota', '0011_agenda_acesso_veiculo_acesso_prestador_acesso_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acesso_pessoa',
            old_name='id_agenda',
            new_name='id_pessoa',
        ),
        migrations.RenameField(
            model_name='acesso_prestador',
            old_name='id_agenda',
            new_name='id_prestador',
        ),
        migrations.RenameField(
            model_name='acesso_veiculo',
            old_name='id_agenda',
            new_name='id_veiculo',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='obs_agenda',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
